package com.example.util;

public class Cities {
    public static String[] getCities() {
        return cities;
    }
    public static String[] cities = new String[] {
            "Shanghai", "Delhi", "Karatschi", "Peking", "Shenzhen", "Kinshasa", "Guangzhou", "Lagos", "İstanbul",
            "Bengaluru", "Chengdu", "Mumbai", "Moskau", "Lahore", "São Paulo", "Tianjin", "Jakarta", "Wuhan", "Dhaka",
            "Hyderabad", "Kairo", "Tokio", "Chennai", "Lima", "Dongguan", "Seoul", "Chongqing", "Xi’an", "Hangzhou",
            "Luanda", "Foshan", "Teheran", "London", "Mexiko-Stadt", "New York City", "Ahmedabad", "Bogotá", "Surat",
            "Nanjing", "Hongkong", "Shenyang", "Ho-Chi-Minh-Stadt", "Riad", "Bagdad", "Rio de Janeiro", "Zhengzhou",
            "Qingdao", "Kolkata (Kalkutta)", "Suzhou (Jiangsu)", "Singapur", "Bangkok", "Changsha", "Abidjan",
            "Sankt Petersburg", "Jinan", "Daressalam", "Kunming", "Alexandria", "Harbin", "Sydney", "Santiago de Chile",
            "Ankara", "Shijiazhuang", "Hefei", "Melbourne", "Dalian", "Johannesburg", "Cape Town (Kapstadt)", "Rangun",
            "Xiamen", "Nanning", "Changchun", "Kabul", "Nairobi", "Gizeh", "Kano", "Taiyuan", "eThekwini (Durban)",
            "Bamako", "Jaipur", "Ekurhuleni", "Tshwane (Pretoria)", "Neu-Taipeh", "Guiyang", "Wuxi", "Pune", "Shantou",
            "Ibadan", "Ürümqi", "Los Angeles", "Zhongshan", "Abuja", "Lucknow", "Yokohama", "Berlin", "Ningbo",
            "Fuzhou", "Dschidda", "Hanoi", "Nanchang", "Addis Abeba", "Port Harcourt", "Casablanca", "Busan", "Madrid",
            "Dubai", "Chittagong", "Faisalabad", "Kanpur", "Changzhou", "Buenos Aires", "Pjöngjang", "Lanzhou",
            "Maschhad", "Nantong", "Surabaya", "Quezon City", "Taschkent", "Kiew", "Izmir", "Incheon", "Brasília",
            "Kumasi", "Algier", "Mbuji-Mayi", "Nagpur", "Rom", "Xuzhou", "Taichung", "Lubumbashi", "Toronto",
            "Douala", "Kaohsiung", "Yaoundé", "Osaka", "Zibo", "Linyi", "Quito", "Chicago", "Gazipur", "Dakar",
            "Baku", "Medellín", "Salvador", "Taipeh", "Fortaleza", "Wenzhou", "Santo Domingo", "Brisbane", "Tangshan",
            "Sanaa", "Bandung", "Lusaka", "Ouagadougou", "Bekasi", "Indore", "Medan", "Daegu", "Omdurman",
            "Belo Horizonte", "Mekka", "Hohhot", "Haikou", "Shaoxing", "Nagoya", "Mogadischu", "Accra", "Houston",
            "Phnom Penh", "Guayaquil", "Taoyuan", "Cali", "Zhuhai", "Paris", "Liuzhou", "Perth", "Lomé", "Almaty",
            "Havanna", "Baotou", "Damaskus", "Aleppo", "Rawalpindi", "Handan", "Huizhou", "Caracas", "Manaus", "Bursa",
            "Weifang", "Gujranwala", "Wien", "Minsk", "Kuala Lumpur", "Brazzaville", "Khartum", "Sapporo", "Peschawar",
            "Al-Chartum Bahri", "Isfahan", "Benin City", "Baoding", "Santa Cruz de la Sierra", "Tangerang", "Depok",
            "Luoyang", "Hamburg", "Tainan", "Multan", "Curitiba", "Warschau", "Manila", "Bukarest", "Amman", "Tijuana",
            "Datong", "Huaiyin", "Yantai", "Bhopal", "Jiangmen", "Adana", "Ganzhou", "Maracaibo", "Budapest", "Kigali",
            "Hyderabad", "Visakhapatnam", "Pimpri-Chinchwad", "Montreal", "Semarang", "Xianyang", "Belgrad", "Patna",
            "Gaziantep", "Kampala", "Monrovia", "Xining", "Zunyi", "Palembang", "Vadodara", "Caloocan", "Conakry",
            "Kunshan", "Beirut", "Ecatepec de Morelos", "Barcelona", "Ghaziabad", "Nowosibirsk", "Auckland",
            "Phoenix", "Ludhiana", "Fukuoka", "Daqing", "Kisangani", "Wuhu", "Karadsch", "León", "Philadelphia", "Agra",
            "Schiras", "Tabriz", "Jekaterinburg", "Puebla", "Putian", "Kawasaki", "Kōbe", "Qinhuangdao", "Jilin",
            "München", "Ciudad Juárez", "Recife", "Daejeon", "Nashik", "Harare", "Yiwu", "Anshan", "Gwangju", "Quanzhou",
            "Kyōto", "Ulaanbaatar", "Cixi", "San Antonio", "Charkiw", "Davao City", "Makassar", "Tai’an", "Goiânia",
            "Medina", "Nanyang", "Faridabad", "Porto Alegre", "Zhanjiang", "Dammam", "Guadalajara", "San Diego",
            "Montevideo", "Belém", "Mailand", "Guarulhos", "Konya", "Mossul", "Guilin", "Tangerang Selatan", "Yancheng",
            "Zaozhuang", "Taizhou", "Shangrao", "Basra", "Astana", "Jiangyin", "Nouakchott", "Saitama", "Antalya",
            "Córdoba", "Adelaide", "Meerut", "Kasan", "Maoming", "Calgary", "Prag", "Heze", "Dallas", "Rajkot",
            "Onitsha", "Yichang", "Schardscha", "Antananarivo", "Xinxiang", "Abu Dhabi", "Zapopan", "Nanchong",
            "Chaozhou", "Bukavu", "Kalyan-Dombivli", "Jieyang", "Schubra al-Chaima", "Huainan", "Sofia", "Changshu",
            "Fushun", "Lilongwe", "Nischni Nowgorod", "Mandalay", "Barranquilla", "Vasai-Virar", "Suwon", "Varanasi",
            "Ghom", "Hiroshima", "Qingyuan", "Batam", "Kaifeng", "Srinagar", "Xianyang", "Fuyang", "Nelson Mandela Bay (Gqeberha)",
            "Tscheljabinsk", "Jiaxing", "Anyang", "Krasnojarsk", "Fès", "Hengyang", "Ahvaz", "Schymkent", "Tripolis", "Samara",
            "Jinjiang", "Aurangabad", "Campinas", "Kananga", "Bandar Lampung", "Dhanbad", "Naypyidaw", "Yinchuan", "Barquisimeto", "Kaduna", "Rizhao",
            "Ufa", "Monterrey", "Rostow am Don", "Birmingham", "Dazhou", "Ulsan", "Amritsar", "Luzhou", "Omsk", "Yueyang",
            "Zhenjiang", "Bischkek", "Navi Mumbai", "Prayagraj", "Baoji", "Mwanza", "Maputo", "Yibin", "Changde", "Krasnodar", "Sendai",
            "Chifeng", "N’Djamena", "Diyarbakır", "Tanger", "Köln", "Huzhou", "Tiflis", "Suqian", "Wanzhou", "Bengbu", "Jerewan",
            "Yangzhou", "Ranchi", "Nezahualcóyotl", "Haora", "Lu’an", "Ottawa", "Yongin", "Tegucigalpa", "Coimbatore", "São Luís",
            "Managua", "Woronesch", "Zhangjiagang", "Jabalpur", "Gwalior", "Vijayawada", "Changzhi", "Pingdingshan", "Goyang",
            "Bogor", "Jinhua", "Mersin", "Zhaoqing", "San José", "Asmara", "Perm", "Jodhpur", "Matola", "Pointe-Noire",
            "Shangqiu", "Qiqihar", "Changwon", "Cartagena", "Wolgograd", "Niamey", "Jinzhou", "Tshikapa", "Liaocheng",
            "Madurai", "Xinyang", "Yuyao", "Rui’an", "Edmonton", "Odessa", "Raipur", "Islamabad", "Arequipa", "Kota", "Quetta"
    };
}
